/*
 * Copyright (C) 2020-2024 CZ.NIC z.s.p.o. (https://www.nic.cz/)
 *
 * This is free software, licensed under the GNU General Public License v3.
 * See /LICENSE for more information.
 */

import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faCheckCircle,
    faQuestionCircle,
    faSquare,
    faTimesCircle,
} from "@fortawesome/free-regular-svg-icons";
import {
    faAngleRight,
    faAngleUp,
    faBars,
    faBell,
    faBox,
    faChartLine,
    faCheck,
    faChevronRight,
    faCircleHalfStroke,
    faCircleQuestion,
    faCog,
    faEdit,
    faEthernet,
    faExternalLinkAlt,
    faFileDownload,
    faForward,
    faHdd,
    faInfoCircle,
    faMinus,
    faMoon,
    faNetworkWired,
    faNewspaper,
    faPlus,
    faPowerOff,
    faQrcode,
    faRightFromBracket,
    faSignal,
    faSlash,
    faStepForward,
    faSun,
    faSyncAlt,
    faTimes,
    faTrash,
    faUserCog,
    faWifi,
} from "@fortawesome/free-solid-svg-icons";

library.add(
    faAngleRight,
    faAngleUp,
    faBars,
    faBell,
    faBox,
    faChartLine,
    faCheck,
    faCheckCircle,
    faChevronRight,
    faCircleHalfStroke,
    faCircleQuestion,
    faCog,
    faEdit,
    faEthernet,
    faExternalLinkAlt,
    faFileDownload,
    faForward,
    faHdd,
    faInfoCircle,
    faMinus,
    faMoon,
    faNetworkWired,
    faNewspaper,
    faPlus,
    faPowerOff,
    faSquare,
    faQrcode,
    faQuestionCircle,
    faRightFromBracket,
    faSignal,
    faSlash,
    faStepForward,
    faSun,
    faSyncAlt,
    faTimes,
    faTimesCircle,
    faTrash,
    faUserCog,
    faWifi
);
